---

- name: Ensure systemd is present
  ansible.builtin.package:
    name: systemd
    state: present

- name: Ensure override folder exists
  ansible.builtin.file:
    dest: /etc/systemd/system/kvrocks.service.d
    state: directory
    mode: '0755'

- name: Review kvrocks systemd options
  ansible.builtin.template:
    src: systemd-override-kvrocks.conf.j2
    dest: /etc/systemd/system/kvrocks.service.d/hardening.conf
    mode: '0644'
  notify:
    - reload systemd
    - restart kvrocks
