---

- name: Verify
  hosts: kvrocks
  gather_facts: false
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Validate that needed packages are present
      ansible.builtin.assert:
        that: ansible_facts.packages['kvrocks']

    - name: Check kvrocks binary file
      ansible.builtin.stat:
        path: /www/kvrocks/bin/kvrocks
      register: bin1
    - name: Validate kvrocks binary is present
      ansible.builtin.assert:
        that: bin1.stat.exists and bin1.stat.size != 0
